name: Test
on:
  pull_request:
  push:
  schedule:
    # first of each month
    - cron: '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian11
          #- debian10
        python-version:
          - '3.9'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies for ${{ matrix.python-version }}
      run: |
        sudo apt-get install python3-yaml python3-jinja2 python3-virtualenv python3-setuptools
        sudo pip3 install pylint PyYAML Jinja2
        sudo pip3 install -U --force-reinstall setuptools==44.1.1 wheel==0.34.2
        #pip install -U pylint PyYAML Jinja2 setuptools==44.1.1 wheel==0.34.2 ujson
    - name: Install make
      run: sudo apt-get install make
    - name: lsb_release
      run: lsb_release -a
    - name: test install with virtualenv and run some tests
      run: PYVERSIONS=python${{ matrix.python-version }} make testinstallvirtualenv
